version: '3'
services:
  node1:
    image: 891335278704.dkr.ecr.us-east-1.amazonaws.com/netvote/${image_name}
    network_mode: host
    restart: always
    environment:
      - BOOTNODE_IP_PORT=${bootnode_ip_port}
      - RPC_ADDR=0.0.0.0
      - RPC_DOMAIN=http://${alb_domain}