version: '3'
services:
  node:
    image: 891335278704.dkr.ecr.us-east-1.amazonaws.com/netvote/${image_name}
    network_mode: host
    restart: always
    volumes:
      - ./geth:/root/node/geth
    environment:
      - BOOTNODE_IP_PORT=${bootnode_ip_port}
      - RPC_ADDR=0.0.0.0
      - RPC_DOMAIN=${netvote_eth_url}